spring.application.name=Task Manager
spring.datasource.url=jdbc:postgresql://localhost:5432/nau-java-taskmanager-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update